import { useState, useRef, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Sparkles, Send, Loader2, Bot, User as UserIcon, Trash2, Copy, Info } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import ReactMarkdown from "react-markdown";

type Msg = { role: "user" | "assistant"; content: string };

const MODELS = [
  { value: "gemini-flash", label: "Google Gemini Flash" },
  { value: "gemini-pro", label: "Google Gemini 2.5 Pro" },
  { value: "chatgpt", label: "OpenAI ChatGPT (GPT-5)" },
  { value: "gpt-5-mini", label: "OpenAI GPT-5 Mini" },
  { value: "claude", label: "Anthropic Claude 3.5 Sonnet" },
  { value: "deepseek", label: "DeepSeek V3" },
];

const MODEL_LABEL: Record<string, string> = Object.fromEntries(MODELS.map(m => [m.value, m.label]));

const TASKS = [
  { value: "general", label: "General assistant", prompt: "" },
  { value: "lesson", label: "Lesson planning", prompt: "Create a detailed lesson plan for: " },
  { value: "admin", label: "Admin writing", prompt: "Draft a professional memo about: " },
  { value: "grading", label: "Grading & feedback", prompt: "Write constructive feedback for a student who: " },
  { value: "email", label: "Email to parents", prompt: "Draft an email to a parent regarding: " },
];

function buildDemoReply(task: string, model: string, prompt: string): string {
  const modelName = MODEL_LABEL[model] ?? model;
  const topic = prompt.replace(/^(Create a detailed lesson plan for:|Draft a professional memo about:|Write constructive feedback for a student who:|Draft an email to a parent regarding:)\s*/i, "").trim() || "your request";
  const header = `*Demo response generated by **${modelName}** — for demonstration only.*\n\n`;

  switch (task) {
    case "lesson":
      return header +
`## Lesson Plan: ${topic}

**Form / Grade:** Form 3  |  **Duration:** 40 minutes

### 1. Learning Objectives
By the end of this lesson, learners should be able to:
- Define the key concepts related to *${topic}*.
- Apply the concepts to a real-world Zimbabwean context.
- Evaluate at least two worked examples.

### 2. Materials
- Textbook (relevant chapter), whiteboard & markers, printed worksheet, projector.

### 3. Lesson Flow
| Time | Activity |
|------|----------|
| 0–5 min | Starter: recall question on the board |
| 5–15 min | Teacher-led explanation with diagram |
| 15–30 min | Pair work on worksheet |
| 30–37 min | Plenary discussion, address misconceptions |
| 37–40 min | Homework: 3 short-answer questions |

### 4. Assessment
- Observation during pair work and an exit-ticket one-liner.

### 5. Differentiation
- **Support:** sentence starters and a glossary card.
- **Stretch:** an application-level extension question.`;

    case "admin":
      return header +
`**MEMORANDUM**

**To:** All Staff
**From:** The Office of the Director
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}
**Subject:** ${topic}

Dear Colleagues,

This memo serves to formally communicate updates regarding **${topic}**. Please note:

1. The matter has been reviewed by senior management.
2. Implementation will be phased over the next two weeks.
3. Heads of Department are kindly requested to brief their teams.

Your cooperation in ensuring a smooth rollout is greatly appreciated.

Yours sincerely,
**Mr. F.J. Moyo**
Director`;

    case "grading":
      return header +
`### Feedback Comment

**Strengths:** The student demonstrates a developing understanding of the topic and shows commendable effort. Their willingness to attempt challenging questions is encouraging.

**Areas to improve:**
- Strengthen accuracy in calculations / grammar.
- Provide more detailed explanations supported by examples.
- Review the section on *${topic}* before the next assessment.

**Next steps:** With consistent practice this learner can confidently move up. Suggested grade band: **C → B**.`;

    case "email":
      return header +
`**Subject:** Update regarding ${topic}

Dear Parent / Guardian,

I trust this email finds you well. I am writing to update you regarding **${topic}** concerning your child.

We have observed positive progress in several areas; however, there are a few aspects we would like to bring to your attention. Continued support at home — particularly with reading practice and completing assignments — will make a meaningful difference.

Please feel free to schedule a brief meeting at your convenience.

Kind regards,
**Class Teacher**
MavingTech Business Solutions Demo School`;

    default:
      return header +
`Here is a thoughtful response to: **${topic}**

- This demonstrates how the AI assistant streams answers in real time.
- In the live deployment this response would come directly from **${modelName}** via a secure backend.
- Switch models from the dropdown and try asking for lesson plans, memos, feedback or parent emails.

Try selecting **Lesson planning** and asking:
> "Plan a 40-minute Form 2 English lesson on persuasive writing."`;
  }
}

export default function TeacherAIAssistant() {
  const { toast } = useToast();
  const [model, setModel] = useState("gemini-flash");
  const [task, setTask] = useState("general");
  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const [streaming, setStreaming] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, streaming]);

  const send = async () => {
    if (!input.trim() || streaming) return;
    const userMsg: Msg = { role: "user", content: input.trim() };
    const next = [...messages, userMsg];
    setMessages(next);
    setInput("");
    setStreaming(true);

    let assistantSoFar = "";
    const upsert = (chunk: string) => {
      assistantSoFar += chunk;
      setMessages(prev => {
        const last = prev[prev.length - 1];
        if (last?.role === "assistant") {
          return prev.map((m, i) => i === prev.length - 1 ? { ...m, content: assistantSoFar } : m);
        }
        return [...prev, { role: "assistant", content: assistantSoFar }];
      });
    };

    // DEMO MODE: simulated streaming response — no API key needed.
    try {
      const reply = buildDemoReply(task, model, userMsg.content);
      const tokens = reply.match(/\S+\s*|\s+/g) ?? [reply];
      // small initial "thinking" delay
      await new Promise(r => setTimeout(r, 350));
      for (const t of tokens) {
        await new Promise(r => setTimeout(r, 20 + Math.random() * 35));
        upsert(t);
      }
    } finally {
      setStreaming(false);
    }
  };

  const onTaskChange = (v: string) => {
    setTask(v);
    const t = TASKS.find(x => x.value === v);
    if (t?.prompt && !input) setInput(t.prompt);
  };

  const copy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied to clipboard" });
  };

  return (
    <Card className="border-primary/30">
      <CardHeader>
        <CardTitle className="font-heading flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" /> AI Assistant
          <Badge variant="secondary" className="ml-2">Multi-model</Badge>
        </CardTitle>
        <CardDescription>
          Chat with an AI tutor for lesson plans, admin writing, grading feedback and more. Pick your preferred model and task.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <label className="text-xs font-medium text-muted-foreground mb-1 block">AI Model</label>
            <Select value={model} onValueChange={setModel}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {MODELS.map(m => <SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="text-xs font-medium text-muted-foreground mb-1 block">Task type</label>
            <Select value={task} onValueChange={onTaskChange}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {TASKS.map(t => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="text-[11px] text-muted-foreground flex items-start gap-1.5 bg-muted/40 rounded-md p-2">
          <Info className="h-3.5 w-3.5 mt-0.5 shrink-0" />
          <span>Claude and DeepSeek aren't on the integrated AI gateway yet — selecting them uses a close-equivalent model (GPT-5 or Gemini Pro) automatically.</span>
        </div>

        <ScrollArea className="h-[380px] border rounded-md p-3 bg-background">
          {messages.length === 0 && !streaming && (
            <div className="text-center text-muted-foreground text-sm py-12">
              <Bot className="h-10 w-10 mx-auto mb-2 opacity-40" />
              Start a conversation. Try: <em>"Plan a 40-min Form 3 lesson on photosynthesis"</em>.
            </div>
          )}
          <div className="space-y-3">
            {messages.map((m, i) => (
              <div key={i} className={`flex gap-2 ${m.role === "user" ? "justify-end" : "justify-start"}`}>
                {m.role === "assistant" && <Bot className="h-5 w-5 text-primary shrink-0 mt-1" />}
                <div className={`rounded-lg px-3 py-2 max-w-[85%] text-sm ${m.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted"}`}>
                  {m.role === "assistant" ? (
                    <div className="prose prose-sm dark:prose-invert max-w-none [&_p]:my-1 [&_ul]:my-1 [&_h1]:text-base [&_h2]:text-sm [&_h3]:text-sm">
                      <ReactMarkdown>{m.content || "…"}</ReactMarkdown>
                      {m.content && (
                        <Button size="sm" variant="ghost" className="h-6 px-2 -ml-2 mt-1" onClick={() => copy(m.content)}>
                          <Copy className="h-3 w-3 mr-1" /> Copy
                        </Button>
                      )}
                    </div>
                  ) : (
                    <div className="whitespace-pre-wrap">{m.content}</div>
                  )}
                </div>
                {m.role === "user" && <UserIcon className="h-5 w-5 text-muted-foreground shrink-0 mt-1" />}
              </div>
            ))}
            {streaming && messages[messages.length - 1]?.role === "user" && (
              <div className="flex gap-2"><Bot className="h-5 w-5 text-primary" /><div className="bg-muted rounded-lg px-3 py-2 text-sm"><Loader2 className="h-4 w-4 animate-spin" /></div></div>
            )}
            <div ref={endRef} />
          </div>
        </ScrollArea>

        <div className="flex gap-2">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }}
            placeholder="Ask anything — lesson ideas, parent emails, grading feedback…"
            className="min-h-[60px] resize-none"
            disabled={streaming}
          />
          <div className="flex flex-col gap-2">
            <Button onClick={send} disabled={streaming || !input.trim()}>
              {streaming ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
            </Button>
            {messages.length > 0 && (
              <Button variant="outline" size="icon" onClick={() => setMessages([])} disabled={streaming} title="Clear chat">
                <Trash2 className="h-4 w-4" />
              </Button>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
